### ISSUE TITLE
testing a new file

### ISSUE THREAD

**Issue by rohithkodali** [philipperemy/speaker-change-detection#1]
Hi,

  is there any way that we can test for a new audio file?

**Comment by philipperemy** [comment]
Not very easily but should be def possible!
Maybe you could work on it and submit a PR?
I'd be happy to review it!

**Comment by philipperemy** [comment]
Added the contribution section in the README: https://github.com/philipperemy/speaker-change-detection/commit/b5dabdda28a03693e7b697feb7f68e7afcb5ef21
